language: node-js
node_js: 
  - 13
services:
  - docker
# pretesting installs
install:
  - echo "nothing needs to be installed"
# scripts to be run such as tests
before_script:
  - echo "no tests"
script:
  - docker --version # print the version for logging
  - docker build -t simple-reverse-proxy --build-arg NAME=${NAME} .
  - docker tag simple-reverse-proxy morehwachege/simple-reverse-proxy:latest
after-success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push morehwachege/simple-reverse-proxy